language: python
python:
- '3.5'
install:
- pip3 install .
script:
- python3 run_tests.py

deploy:
  provider: pypi
  user: tomkukral
  password:
    secure: WQ5Uzpmet84pFVd49eBi4qRbbUjmbscrErWzHgBOe8hDc3Al14xPVpGFcavqQRgW3OynV0nUWs6UA0/naDpZGdHQKGTi2PJZls/JadapP2ct7tHWOnLXVB8FvHNonyj1gSzzZNb4H9PTAF6GweDHMCx/VUgc1XeK9TdVREOCHOp2O93HRCw7bD0/piHcpIQdj3SGLdLcSV9fniC3U4nbsyIt7wkZT6sZAmfWDI9BF3Pshu4WVmjv1gDCoowonWT0ny/aTOvxRWgAG5nEClgK1yY+ROFzTVR18t6OPGUBCe50XFdpMfcp/zX6cTfVS0vCVDMbDiiAt8lSwFcluMk3lHZe/0jHzHwU6eWPeJuWMZrRlrP+tV3DTDme6QUn//TPE8/GPjGIoD827JWYxmVFbaeJPshN2s4MqexOJ4j7jvJXH9SR9iWIMatPJbV0ZkUhSILC8f5QSZkU6Q7tSV1XsClqktDr3Do7xnQTnQfUcx9e0ggAMPltDT3yIt+B8XKNoWN4ZX9ef1bfM4UhZF1Vw2t93CGLeQWZsLVlU9AM0WcMwk64D+QbCA0p9RuTHUHnMj2FvGInRcrkpLjPzAhj5lCiRilkT+SLbyzWH/uR7KtiSSWKN6b2X+QTW/duScZTuuQpInijROjD3UTg5gFSSjAFLjpzC+2NyNicNIZqBhw=
  on:
    tags: true
    repo: tomkukral/npimp
